// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheDialgaTeam.Pokemon3D.Server.Core.Database;

#nullable disable

namespace TheDialgaTeam.Pokemon3D.Server.Core.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231208172602_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.BannedPlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId")
                        .IsUnique();

                    b.ToTable("BannedPlayerProfiles");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.BlockedPlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockedProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockedProfileId");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("BlockedPlayerProfiles");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.LocalWorld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DoDayCycle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weather")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId")
                        .IsUnique();

                    b.ToTable("LocalWorlds");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameJoltId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.BannedPlayerProfile", b =>
                {
                    b.HasOne("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.PlayerProfile", "PlayerProfile")
                        .WithOne("Blacklist")
                        .HasForeignKey("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.BannedPlayerProfile", "PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.BlockedPlayerProfile", b =>
                {
                    b.HasOne("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.PlayerProfile", "BlockedProfile")
                        .WithMany()
                        .HasForeignKey("BlockedProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.PlayerProfile", "PlayerProfile")
                        .WithMany("BlockProfiles")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedProfile");

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.LocalWorld", b =>
                {
                    b.HasOne("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.PlayerProfile", "PlayerProfile")
                        .WithOne("LocalWorld")
                        .HasForeignKey("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.LocalWorld", "PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Tables.PlayerProfile", b =>
                {
                    b.Navigation("Blacklist");

                    b.Navigation("BlockProfiles");

                    b.Navigation("LocalWorld")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
