// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheDialgaTeam.Pokemon3D.Server.Core.Database;

#nullable disable

namespace TheDialgaTeam.Pokemon3D.Server.Core.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.BannedPlayerProfile", b =>
                {
                    b.Property<int>("PlayerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerProfileId");

                    b.ToTable("BannedPlayerProfiles");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.BlockedPlayerProfile", b =>
                {
                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockedProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerProfileId", "BlockedProfileId");

                    b.HasIndex("BlockedProfileId");

                    b.ToTable("BlockedPlayerProfiles");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.LocalWorld", b =>
                {
                    b.Property<int>("PlayerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DoDayCycle")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weather")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerProfileId");

                    b.ToTable("LocalWorlds");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.PlayerProfile", b =>
                {
                    b.Property<int>("PlayerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("GameJoltId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerProfileId");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.HasIndex("GameJoltId");

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.BannedPlayerProfile", b =>
                {
                    b.HasOne("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.PlayerProfile", null)
                        .WithOne()
                        .HasForeignKey("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.BannedPlayerProfile", "PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.BlockedPlayerProfile", b =>
                {
                    b.HasOne("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("BlockedProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.PlayerProfile", null)
                        .WithMany("BlockProfiles")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.LocalWorld", b =>
                {
                    b.HasOne("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.PlayerProfile", null)
                        .WithOne("LocalWorld")
                        .HasForeignKey("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.LocalWorld", "PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Core.Database.Entities.PlayerProfile", b =>
                {
                    b.Navigation("BlockProfiles");

                    b.Navigation("LocalWorld")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
