//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDialgaTeam.Pokemon3D.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheDialgaTeam.Pokemon3D.Server.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been away for too long..
        /// </summary>
        internal static string SERVER_AFK {
            get {
                return ResourceManager.GetString("SERVER_AFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been banned from server. Reason: {0} | Ban duration: {1}.
        /// </summary>
        internal static string SERVER_BLACKLISTED {
            get {
                return ResourceManager.GetString("SERVER_BLACKLISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0} ({1})&gt;: {2}.
        /// </summary>
        internal static string SERVER_CHAT_GAMEJOLT {
            get {
                return ResourceManager.GetString("SERVER_CHAT_GAMEJOLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;: {1}.
        /// </summary>
        internal static string SERVER_CHAT_NO_GAMEJOLT {
            get {
                return ResourceManager.GetString("SERVER_CHAT_NO_GAMEJOLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are still in the server. Contact the server administrator for help..
        /// </summary>
        internal static string SERVER_CLONE {
            get {
                return ResourceManager.GetString("SERVER_CLONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server has been shut down or lost its connection. Sorry for the inconveniences caused..
        /// </summary>
        internal static string SERVER_CLOSE {
            get {
                return ResourceManager.GetString("SERVER_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Command] {0} ({1}) {2}.
        /// </summary>
        internal static string SERVER_COMMAND_GAMEJOLT {
            get {
                return ResourceManager.GetString("SERVER_COMMAND_GAMEJOLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Command] {0} {1}.
        /// </summary>
        internal static string SERVER_COMMAND_NO_GAMEJOLT {
            get {
                return ResourceManager.GetString("SERVER_COMMAND_NO_GAMEJOLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required permission to use this command..
        /// </summary>
        internal static string SERVER_COMMAND_PERMISSION {
            get {
                return ResourceManager.GetString("SERVER_COMMAND_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have required permission to join the server..
        /// </summary>
        internal static string SERVER_DISALLOW {
            get {
                return ResourceManager.GetString("SERVER_DISALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server is currently full of players..
        /// </summary>
        internal static string SERVER_FULL {
            get {
                return ResourceManager.GetString("SERVER_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) {2}.
        /// </summary>
        internal static string SERVER_GAMEJOLT {
            get {
                return ResourceManager.GetString("SERVER_GAMEJOLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package data sent. Please ensure that you are using the latest version of the game..
        /// </summary>
        internal static string SERVER_INVALID_DATA {
            get {
                return ResourceManager.GetString("SERVER_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been ip banned from server. Reason: {0} | Ban duration: {1}.
        /// </summary>
        internal static string SERVER_IP_BLACKLISTED {
            get {
                return ResourceManager.GetString("SERVER_IP_BLACKLISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to kick yourself. For your personal safety, we will not kick you :).
        /// </summary>
        internal static string SERVER_KICK_SELF {
            get {
                return ResourceManager.GetString("SERVER_KICK_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been kicked from the server with the following reason: {0}.
        /// </summary>
        internal static string SERVER_KICKED {
            get {
                return ResourceManager.GetString("SERVER_KICKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have played in the server for {0} hour(s). We encourage your stay but also encourage you to take a small break :).
        /// </summary>
        internal static string SERVER_LOGIN_TIME {
            get {
                return ResourceManager.GetString("SERVER_LOGIN_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been muted in the server. Reason: {0} | Ban duration: {1}.
        /// </summary>
        internal static string SERVER_MUTED {
            get {
                return ResourceManager.GetString("SERVER_MUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server do not allow players to chat..
        /// </summary>
        internal static string SERVER_NO_CHAT {
            get {
                return ResourceManager.GetString("SERVER_NO_CHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string SERVER_NO_GAMEJOLT {
            get {
                return ResourceManager.GetString("SERVER_NO_GAMEJOLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a slow connection or you have been disconnected from the internet for too long.
        /// </summary>
        internal static string SERVER_NO_PING {
            get {
                return ResourceManager.GetString("SERVER_NO_PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested player is not an operator..
        /// </summary>
        internal static string SERVER_NOT_OPERATOR {
            get {
                return ResourceManager.GetString("SERVER_NOT_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server do not allow offline player..
        /// </summary>
        internal static string SERVER_OFFLINE_MODE {
            get {
                return ResourceManager.GetString("SERVER_OFFLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have left the server..
        /// </summary>
        internal static string SERVER_PLAYER_LEFT {
            get {
                return ResourceManager.GetString("SERVER_PLAYER_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested player does not exist in the server..
        /// </summary>
        internal static string SERVER_PLAYER_NOT_EXIST {
            get {
                return ResourceManager.GetString("SERVER_PLAYER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server do not allow players to PvP..
        /// </summary>
        internal static string SERVER_PVP_DISALLOW {
            get {
                return ResourceManager.GetString("SERVER_PVP_DISALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to use this party due to the following reason: {0}.
        /// </summary>
        internal static string SERVER_PVP_VALIDATION {
            get {
                return ResourceManager.GetString("SERVER_PVP_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server is restarting. Sorry for the inconveniences caused..
        /// </summary>
        internal static string SERVER_RESTART {
            get {
                return ResourceManager.GetString("SERVER_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is scheduled to restart in {0}. Please save your game to avoid losing progress..
        /// </summary>
        internal static string SERVER_RESTART_WARNING {
            get {
                return ResourceManager.GetString("SERVER_RESTART_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be unique :) Do not send the same message again in quick succession..
        /// </summary>
        internal static string SERVER_SPAM {
            get {
                return ResourceManager.GetString("SERVER_SPAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server do not allow players to trade..
        /// </summary>
        internal static string SERVER_TRADE_DISALLOW {
            get {
                return ResourceManager.GetString("SERVER_TRADE_DISALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is scheduled to restart in {0}. For your personal safety, starting a new trade or PvP is disabled..
        /// </summary>
        internal static string SERVER_TRADE_PVP_FAIL {
            get {
                return ResourceManager.GetString("SERVER_TRADE_PVP_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server require you to play the following gamemodes: {0}.
        /// </summary>
        internal static string SERVER_WRONG_GAMEMODE {
            get {
                return ResourceManager.GetString("SERVER_WRONG_GAMEMODE", resourceCulture);
            }
        }
    }
}
