// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheDialgaTeam.Pokemon3D.Server.Database;

namespace TheDialgaTeam.Pokemon3D.Server.Migrations
{
    [DbContext(typeof(SqliteDatabaseContext))]
    [Migration("20210428094111_0.1.0.0")]
    partial class _0100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Database.Tables.Blacklist", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameJoltId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Blacklists");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Database.Tables.IPBlacklist", b =>
                {
                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("IPAddress");

                    b.ToTable("IpBlacklists");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Database.Tables.MuteList", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameJoltId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("MuteLists");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Database.Tables.OperatorList", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameJoltId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("OperatorLists");
                });

            modelBuilder.Entity("TheDialgaTeam.Pokemon3D.Server.Database.Tables.Whitelist", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameJoltId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Whitelists");
                });
#pragma warning restore 612, 618
        }
    }
}
